start_time: "20220601_0000"
end_time: "20220901_0000"
Resample: True
pole_split: True
struct_boundary_date: "20210101_0000"
pole_folders: ["np", "sp"]

aux_fps:
  {
    "np": "/wolke_scratch/dnikolo/CLAAS_Data/np/CM_SAF_CLAAS3_L2_AUX.nc",
    "sp": "/wolke_scratch/dnikolo/CLAAS_Data/sp/CM_SAF_CLAAS3_L2_AUX.nc",
  }
  
#Leave empy if no name
CLAAS_fp: "n2o:/wolke_scratch/dnikolo/CLAAS_Data/"
job_output_fp: "/cluster/work/climate/dnikolo/Job_output/"

agg_fact: 3

t_deltas: [3,5]

postprocessing_fast_mode: False
fast_mode_arr_size: 20000
write_csv: True
#Folder for postprocessing
postprocessing_output_dir: /cluster/work/climate/dnikolo/Cloud_analysis/
time_folder_format: "%Y%m%d.%H%M"
