start_time: "20220301_0000"
end_time: "20220401_0000"
Resample: False
pole_split: True
struct_boundary_date: "20210101_0000"
pole_folders: ["np", "sp"]

aux_fps:
  {
    "np": "/wolke_scratch/dnikolo/CLAAS_Data/np/CM_SAF_CLAAS3_L2_AUX.nc",
    "sp": "/wolke_scratch/dnikolo/CLAAS_Data/sp/CM_SAF_CLAAS3_L2_AUX.nc",
  }
  
aux_fps_eu:
  {
    "np": "/cluster/work/climate/dnikolo/Auxiliary_files/CM_SAF_CLAAS3_L2_AUX_NP.nc",
    "sp": "/cluster/work/climate/dnikolo/Auxiliary_files/CM_SAF_CLAAS3_L2_AUX_NP.nc",
  }  
#Leave empy if no name
CLAAS_fp: "n2o:/wolke_scratch/dnikolo/CLAAS_Data/"
job_output_fp: "eu:/cluster/work/climate/dnikolo/Job_output/"

agg_fact: 3

t_deltas: [9,6,5,3]

postprocessing_fast_mode: False
fast_mode_arr_size: 20000
write_csv: True
#Folder for postprocessing
postprocessing_output_dir: /cluster/work/climate/dnikolo/Cloud_analysis/
time_folder_format: "%Y%m%d.%H%M"
